wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1648741925
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      2:
      - 1
      - 37
      - 38
      - 41
      3:
      - 13
      - 16
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
checkpoint_config:
  desc: null
  value:
    interval: 1
    max_keep_ckpts: 2
    save_last: true
classes:
  desc: null
  value:
  - General trash
  - Paper
  - Paper pack
  - Metal
  - Glass
  - Plastic
  - Styrofoam
  - Plastic bag
  - Battery
  - Clothing
custom_hooks:
  desc: null
  value:
  - type: NumClassCheckHook
data:
  desc: null
  value:
    samples_per_gpu: 2
    test:
      ann_file: ../../dataset/test.json
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: ../../dataset/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 1024
        - 1024
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.6506697
          - 117.39730243
          - 110.07542563
          std:
          - 54.03457934
          - 53.36968771
          - 54.78390763
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    train:
      ann_file: ../../dataset/clear_fold_0_train.json
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: ../../dataset/
      pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
        with_bbox: true
      - flip_ratio: 0.5
        type: RandomFlip
      - img_scale:
        - - 1024
          - 1024
        keep_ratio: true
        ratio_range:
        - 0.5
        - 1.5
        type: Resize
      - cutout_shape:
        - - 4
          - 4
        - - 4
          - 8
        - - 8
          - 4
        - - 8
          - 8
        - - 16
          - 8
        - - 8
          - 16
        - - 16
          - 16
        - - 16
          - 32
        - - 32
          - 16
        - - 32
          - 32
        - - 32
          - 48
        - - 48
          - 32
        - - 48
          - 48
        n_holes:
        - 5
        - 10
        type: CutOut
      - mean:
        - 123.6506697
        - 117.39730243
        - 110.07542563
        std:
        - 54.03457934
        - 53.36968771
        - 54.78390763
        to_rgb: true
        type: Normalize
      - size_divisor: 32
        type: Pad
      - type: DefaultFormatBundle
      - keys:
        - img
        - gt_bboxes
        - gt_labels
        type: Collect
      type: CocoDataset
    val:
      ann_file: ../../dataset/clear_fold_0_val.json
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: ../../dataset/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 1024
        - 1024
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.6506697
          - 117.39730243
          - 110.07542563
          std:
          - 54.03457934
          - 53.36968771
          - 54.78390763
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    workers_per_gpu: 2
data_root:
  desc: null
  value: ../../dataset/
dataset_type:
  desc: null
  value: CocoDataset
dist_params:
  desc: null
  value:
    backend: nccl
evaluation:
  desc: null
  value:
    classwise: true
    interval: 1
    metric: bbox
    save_best: bbox_mAP_50
img_norm_cfg:
  desc: null
  value:
    mean:
    - 123.6506697
    - 117.39730243
    - 110.07542563
    std:
    - 54.03457934
    - 53.36968771
    - 54.78390763
    to_rgb: true
load_from:
  desc: null
  value: null
log_level:
  desc: null
  value: INFO
lr_config:
  desc: null
  value:
    min_lr: 1.0e-06
    policy: CosineAnnealing
    warmup: linear
    warmup_iters: 1000
    warmup_ratio: 0.01
model:
  desc: null
  value:
    backbone:
      attn_drop_rate: 0.0
      convert_weights: true
      depths:
      - 2
      - 2
      - 18
      - 2
      drop_path_rate: 0.2
      drop_rate: 0.0
      embed_dims: 192
      init_cfg:
        checkpoint: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth
        type: Pretrained
      mlp_ratio: 4
      num_heads:
      - 6
      - 12
      - 24
      - 48
      out_indices:
      - 0
      - 1
      - 2
      - 3
      patch_norm: true
      qk_scale: null
      qkv_bias: true
      type: SwinTransformer
      window_size: 12
      with_cp: false
    neck:
      in_channels:
      - 192
      - 384
      - 768
      - 1536
      num_outs: 5
      out_channels: 256
      type: FPN
    roi_head:
      bbox_head:
        bbox_coder:
          target_means:
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          target_stds:
          - 0.1
          - 0.1
          - 0.2
          - 0.2
          type: DeltaXYWHBBoxCoder
        conv_out_channels: 1024
        fc_out_channels: 1024
        in_channels: 256
        loss_bbox:
          beta: 1.0
          loss_weight: 2.0
          type: SmoothL1Loss
        loss_cls:
          loss_weight: 2.0
          type: CrossEntropyLoss
          use_sigmoid: false
        num_classes: 10
        num_convs: 4
        num_fcs: 2
        reg_class_agnostic: false
        roi_feat_size: 7
        type: DoubleConvFCBBoxHead
      bbox_roi_extractor:
        featmap_strides:
        - 4
        - 8
        - 16
        - 32
        out_channels: 256
        roi_layer:
          output_size: 7
          sampling_ratio: 0
          type: RoIAlign
        type: SingleRoIExtractor
      reg_roi_scale_factor: 1.3
      type: DoubleHeadRoIHead
    rpn_head:
      anchor_generator:
        ratios:
        - 0.5
        - 1.0
        - 2.0
        scales:
        - 8
        strides:
        - 4
        - 8
        - 16
        - 32
        - 64
        type: AnchorGenerator
      bbox_coder:
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        type: DeltaXYWHBBoxCoder
      feat_channels: 256
      in_channels: 256
      loss_bbox:
        loss_weight: 1.0
        type: L1Loss
      loss_cls:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: true
      type: RPNHead
    test_cfg:
      rcnn:
        max_per_img: 100
        nms:
          iou_threshold: 0.5
          type: nms
        score_thr: 0.05
      rpn:
        max_per_img: 1000
        min_bbox_size: 0
        nms:
          iou_threshold: 0.7
          type: nms
        nms_pre: 1000
    train_cfg:
      rcnn:
        assigner:
          ignore_iof_thr: -1
          match_low_quality: false
          min_pos_iou: 0.5
          neg_iou_thr: 0.5
          pos_iou_thr: 0.5
          type: MaxIoUAssigner
        debug: false
        pos_weight: -1
        sampler:
          add_gt_as_proposals: true
          neg_pos_ub: -1
          num: 512
          pos_fraction: 0.25
          type: RandomSampler
      rpn:
        allowed_border: -1
        assigner:
          ignore_iof_thr: -1
          match_low_quality: true
          min_pos_iou: 0.3
          neg_iou_thr: 0.3
          pos_iou_thr: 0.7
          type: MaxIoUAssigner
        debug: false
        pos_weight: -1
        sampler:
          add_gt_as_proposals: false
          neg_pos_ub: -1
          num: 256
          pos_fraction: 0.5
          type: RandomSampler
      rpn_proposal:
        max_per_img: 1000
        min_bbox_size: 0
        nms:
          iou_threshold: 0.7
          type: nms
        nms_pre: 2000
    type: FasterRCNN
mp_start_method:
  desc: null
  value: fork
opencv_num_threads:
  desc: null
  value: 0
optimizer:
  desc: null
  value:
    lr: 0.0001
    type: AdamW
    weight_decay: 1.0e-05
optimizer_config:
  desc: null
  value:
    grad_clip: null
resume_from:
  desc: null
  value: null
runner:
  desc: null
  value:
    max_epochs: 50
    type: EpochBasedRunner
test_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - flip: false
    img_scale:
    - 1024
    - 1024
    transforms:
    - keep_ratio: true
      type: Resize
    - type: RandomFlip
    - mean:
      - 123.6506697
      - 117.39730243
      - 110.07542563
      std:
      - 54.03457934
      - 53.36968771
      - 54.78390763
      to_rgb: true
      type: Normalize
    - size_divisor: 32
      type: Pad
    - keys:
      - img
      type: ImageToTensor
    - keys:
      - img
      type: Collect
    type: MultiScaleFlipAug
train_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: LoadAnnotations
    with_bbox: true
  - flip_ratio: 0.5
    type: RandomFlip
  - img_scale:
    - - 1024
      - 1024
    keep_ratio: true
    ratio_range:
    - 0.5
    - 1.5
    type: Resize
  - cutout_shape:
    - - 4
      - 4
    - - 4
      - 8
    - - 8
      - 4
    - - 8
      - 8
    - - 16
      - 8
    - - 8
      - 16
    - - 16
      - 16
    - - 16
      - 32
    - - 32
      - 16
    - - 32
      - 32
    - - 32
      - 48
    - - 48
      - 32
    - - 48
      - 48
    n_holes:
    - 5
    - 10
    type: CutOut
  - mean:
    - 123.6506697
    - 117.39730243
    - 110.07542563
    std:
    - 54.03457934
    - 53.36968771
    - 54.78390763
    to_rgb: true
    type: Normalize
  - size_divisor: 32
    type: Pad
  - type: DefaultFormatBundle
  - keys:
    - img
    - gt_bboxes
    - gt_labels
    type: Collect
workflow:
  desc: null
  value:
  - - train
    - 1
