wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1648633279
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      2:
      - 1
      - 37
      - 38
      - 41
      3:
      - 2
      - 13
      - 16
      4: 3.7.11
      5: 0.12.11
      8:
      - 5
checkpoint_config:
  desc: null
  value:
    interval: 1
classes:
  desc: null
  value:
  - General trash
  - Paper
  - Paper pack
  - Metal
  - Glass
  - Plastic
  - Styrofoam
  - Plastic bag
  - Battery
  - Clothing
custom_hooks:
  desc: null
  value:
  - type: NumClassCheckHook
data:
  desc: null
  value:
    samples_per_gpu: 2
    test:
      ann_file: /opt/ml/detection/dataset/test.json
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: /opt/ml/detection/dataset/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 512
        - 512
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    train:
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: /opt/ml/detection/dataset/
      pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
        with_bbox: true
      - img_scale:
        - 512
        - 512
        keep_ratio: true
        type: Resize
      - flip_ratio: 0.5
        type: RandomFlip
      - mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        to_rgb: true
        type: Normalize
      - size_divisor: 32
        type: Pad
      - type: DefaultFormatBundle
      - keys:
        - img
        - gt_bboxes
        - gt_labels
        type: Collect
      type: CocoDataset
    val:
      classes:
      - General trash
      - Paper
      - Paper pack
      - Metal
      - Glass
      - Plastic
      - Styrofoam
      - Plastic bag
      - Battery
      - Clothing
      img_prefix: /opt/ml/detection/dataset/
      pipeline:
      - type: LoadImageFromFile
      - flip: false
        img_scale:
        - 512
        - 512
        transforms:
        - keep_ratio: true
          type: Resize
        - type: RandomFlip
        - mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
          type: Normalize
        - size_divisor: 32
          type: Pad
        - keys:
          - img
          type: ImageToTensor
        - keys:
          - img
          type: Collect
        type: MultiScaleFlipAug
      type: CocoDataset
    workers_per_gpu: 2
data_root:
  desc: null
  value: /opt/ml/detection/dataset/
dataset_type:
  desc: null
  value: CocoDataset
dist_params:
  desc: null
  value:
    backend: nccl
evaluation:
  desc: null
  value:
    interval: 1
    metric: bbox
    save_best: bbox_mAP_50
img_norm_cfg:
  desc: null
  value:
    mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
load_from:
  desc: null
  value: null
log_config:
  desc: null
  value:
    hooks:
    - type: TextLoggerHook
    interval: 50
log_level:
  desc: null
  value: INFO
lr_config:
  desc: null
  value:
    policy: step
    step:
    - 8
    - 11
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001
model:
  desc: null
  value:
    backbone:
      attn_drop_rate: 0.0
      convert_weights: true
      depths:
      - 2
      - 2
      - 18
      - 2
      drop_path_rate: 0.2
      drop_rate: 0.0
      embed_dims: 192
      init_cfg:
        checkpoint: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window7_224_22kto1k.pth
        type: Pretrained
      mlp_ratio: 4
      num_heads:
      - 6
      - 12
      - 24
      - 48
      out_indices:
      - 0
      - 1
      - 2
      - 3
      patch_norm: true
      qk_scale: null
      qkv_bias: true
      type: SwinTransformer
      window_size: 7
      with_cp: false
    bbox_head:
      anchor_generator:
        octave_base_scale: 8
        ratios:
        - 1.0
        scales_per_octave: 1
        strides:
        - 8
        - 16
        - 32
        - 64
        - 128
        type: AnchorGenerator
      bbox_coder:
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 0.1
        - 0.1
        - 0.2
        - 0.2
        type: DeltaXYWHBBoxCoder
      feat_channels: 256
      in_channels: 256
      loss_bbox:
        loss_weight: 2.0
        type: GIoULoss
      loss_centerness:
        loss_weight: 1.0
        type: CrossEntropyLoss
        use_sigmoid: true
      loss_cls:
        alpha: 0.25
        gamma: 2.0
        loss_weight: 1.0
        type: FocalLoss
        use_sigmoid: true
      num_classes: 10
      stacked_convs: 0
      type: ATSSHead
    neck:
    - add_extra_convs: on_output
      in_channels:
      - 192
      - 384
      - 768
      - 1536
      num_outs: 5
      out_channels: 256
      start_level: 1
      type: FPN
    - in_channels: 256
      num_blocks: 6
      out_channels: 256
      type: DyHead
    test_cfg:
      max_per_img: 100
      min_bbox_size: 0
      nms:
        iou_threshold: 0.6
        type: nms
      nms_pre: 1000
      score_thr: 0.05
    train_cfg:
      allowed_border: -1
      assigner:
        topk: 9
        type: ATSSAssigner
      debug: false
      pos_weight: -1
    type: ATSS
mp_start_method:
  desc: null
  value: fork
opencv_num_threads:
  desc: null
  value: 0
optimizer:
  desc: null
  value:
    betas:
    - 0.9
    - 0.999
    lr: 0.0001
    paramwise_cfg:
      custom_keys:
        absolute_pos_embed:
          decay_mult: 0.0
        norm:
          decay_mult: 0.0
        relative_position_bias_table:
          decay_mult: 0.0
    type: AdamW
    weight_decay: 0.05
optimizer_config:
  desc: null
  value:
    grad_clip: null
pretrained:
  desc: null
  value: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window7_224_22kto1k.pth
resume_from:
  desc: null
  value: null
runner:
  desc: null
  value:
    max_epochs: 12
    type: EpochBasedRunner
test_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - flip: false
    img_scale:
    - 512
    - 512
    transforms:
    - keep_ratio: true
      type: Resize
    - type: RandomFlip
    - mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      to_rgb: true
      type: Normalize
    - size_divisor: 32
      type: Pad
    - keys:
      - img
      type: ImageToTensor
    - keys:
      - img
      type: Collect
    type: MultiScaleFlipAug
train_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: LoadAnnotations
    with_bbox: true
  - img_scale:
    - 512
    - 512
    keep_ratio: true
    type: Resize
  - flip_ratio: 0.5
    type: RandomFlip
  - mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
    type: Normalize
  - size_divisor: 32
    type: Pad
  - type: DefaultFormatBundle
  - keys:
    - img
    - gt_bboxes
    - gt_labels
    type: Collect
workflow:
  desc: null
  value:
  - - train
    - 1
